loot = {
    "weapons, basic": { "dagger": {"attack": 3, "value": 1},
                        "shortsword": {"attack": 5, "value": 3},
                        "longsword": {"attack": 8, "value": 5},
                        "greatsword": {"attack": 12, "value": 20},
                        "greataxe": {"attack": 12, "value": 8},
                        "shortbow": {"attack": 8, "value": 6},
                        "longbow": {"attack": 10, "value": 8},

    },
    "weapons, magic": {"sword of shining": {"attack": 5, "value": 30},
                "dagger of foul stench": {"attack": 3, "value": 20},
                "mace of smashing": {"attack": 7, "value": 80},
                "greatsword of flaming": {"attack": 12, "value": 300},
                "bow of flying": {"attack": 6, "value": 100},
                "scimitar of slashing": {"attack": 5, "value": 50},
                "rapier of dancing": {"attack": 10, "value": 700},
                "sword of the hero": {"attack": 99, "value": 999}
                     }, 
    "armor": {"leather, basic": {"defense": 3, "value": 5},
              "hide, basic": {"defense": 5, "value": 15},
              "studded leather, basic": {"defense": 4, "value": 20},
              "breastplate, basic": {"defense": 6, "value": 30},
              "half plate, basic": {"defense": 9, "value": 45},
              "full plate, basic": {"defense": 15, "value": 60},
              "chain, basic": {"defense": 7, "value": 35},
              "leather, magic": {"defense": 5, "value": 15},
              "hide, magic": {"defense": 7, "value": 20},
              "studded leather, magic": {"defense": 8, "value": 30},
              "breastplate, magic": {"defense": 12, "value": 50},
              "half plate, magic": {"defense": 18, "value": 75},
              "full plate, magic": {"defense": 30, "value": 100},
              "chain, magic": {"defense": 14, "value": 40}

            },
    "misc": { "tattered rags" : {"value": .01},
             "leather scraps" : {"value": .15},
             "copper ore" : {"value": .001},
             "silver ore" : {"value": .01},
             "gold ore" : {"value": .05},
             "copper piece" : {"value": .01},
             "silver piece" : {"value": .1},
             "gold piece" : {"value": 1},
             "platinum ore" : {"value": 10},
             "platinum piece" : {"value": 100},
             "copper ingot" : {"value": 10},
             "silver ingot" : {"value": 100},
             "gold ingot" : {"value": 1_000},
             "platinum ingot" : {"value": 10_000},
             "ark of immortality" : {"value": 1_000_000},

    }
    }